-- V10__create_billing_tables.sql
-- CR05 缴费管理模块建表语句

CREATE TABLE `bl_fee_config` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `community_id` BIGINT NOT NULL COMMENT '小区ID（关联 bs_community.id）',
    `building_id` BIGINT DEFAULT NULL COMMENT '楼栋ID（NULL 表示小区级别配置，关联 bs_building.id）',
    `fee_type` VARCHAR(20) NOT NULL COMMENT '费用类型（PROPERTY_FEE-物业费 PARKING_FEE-停车费 WATER_FEE-水费 ELECTRICITY_FEE-电费 GAS_FEE-燃气费）',
    `billing_method` VARCHAR(20) NOT NULL COMMENT '计费方式（BY_AREA-按面积 FIXED-固定月费 BY_USAGE-按用量）',
    `unit_price` DECIMAL(12,4) NOT NULL COMMENT '单价',
    `due_day` INT DEFAULT NULL COMMENT '缴费截止日（每月几号，NULL 表示使用默认最后一天）',
    `status` VARCHAR(10) NOT NULL DEFAULT 'ENABLED' COMMENT '配置状态（ENABLED-启用 DISABLED-停用）',
    `remark` VARCHAR(256) DEFAULT NULL COMMENT '备注',
    `del_flag` TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记（0-正常 1-删除）',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '创建人',
    `update_by` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '更新人',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_community_building_type` (`community_id`, `building_id`, `fee_type`, `del_flag`),
    KEY `idx_community_id` (`community_id`),
    KEY `idx_building_id` (`building_id`),
    KEY `idx_fee_type` (`fee_type`),
    KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='费用配置表';

CREATE TABLE `bl_bill` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `bill_no` VARCHAR(20) NOT NULL COMMENT '账单编号（BL+年月+6位序号）',
    `batch_no` VARCHAR(28) DEFAULT NULL COMMENT '批次号（批量生成时分配，手动创建为 NULL）',
    `fee_type` VARCHAR(20) NOT NULL COMMENT '费用类型',
    `amount` DECIMAL(12,2) NOT NULL COMMENT '应收金额（原始金额）',
    `reduce_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '减免金额（累计）',
    `paid_amount` DECIMAL(12,2) DEFAULT NULL COMMENT '实付金额',
    `refund_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '退款金额（累计）',
    `status` VARCHAR(20) NOT NULL DEFAULT 'UNPAID' COMMENT '账单状态（UNPAID-待缴费 PAYING-待支付 PAID-已缴费 OVERDUE-已逾期 REDUCED-已减免 REFUNDED-已退款 CANCELLED-已取消）',
    `owner_id` BIGINT NOT NULL COMMENT '业主ID（关联 ow_owner.id）',
    `owner_name` VARCHAR(64) NOT NULL COMMENT '业主姓名（冗余）',
    `house_id` BIGINT NOT NULL COMMENT '房屋ID（关联 bs_house.id）',
    `building_id` BIGINT DEFAULT NULL COMMENT '楼栋ID（冗余）',
    `community_id` BIGINT NOT NULL COMMENT '小区ID（冗余，用于数据权限）',
    `billing_period` VARCHAR(7) NOT NULL COMMENT '账期（格式 yyyy-MM）',
    `due_date` DATE NOT NULL COMMENT '缴费截止日期',
    `usage_amount` DECIMAL(12,2) DEFAULT NULL COMMENT '用量（水电燃气费使用）',
    `unit_price` DECIMAL(12,4) DEFAULT NULL COMMENT '单价（生成时的快照）',
    `house_area` DECIMAL(10,2) DEFAULT NULL COMMENT '房屋面积（生成时的快照，物业费使用）',
    `paid_time` DATETIME DEFAULT NULL COMMENT '缴费时间',
    `reduce_approved` TINYINT NOT NULL DEFAULT 0 COMMENT '减免审批状态（0-无减免 1-待审批 2-已审批 3-已撤销）',
    `cancel_reason` VARCHAR(512) DEFAULT NULL COMMENT '取消原因',
    `remark` VARCHAR(256) DEFAULT NULL COMMENT '备注',
    `del_flag` TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记（0-正常 1-删除）',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '创建人',
    `update_by` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '更新人',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_bill_no` (`bill_no`),
    KEY `idx_batch_no` (`batch_no`),
    KEY `idx_owner_id` (`owner_id`),
    KEY `idx_house_id` (`house_id`),
    KEY `idx_community_id` (`community_id`),
    KEY `idx_building_id` (`building_id`),
    KEY `idx_fee_type` (`fee_type`),
    KEY `idx_status` (`status`),
    KEY `idx_billing_period` (`billing_period`),
    KEY `idx_due_date` (`due_date`),
    KEY `idx_status_due_date` (`status`, `due_date`),
    KEY `idx_owner_status` (`owner_id`, `status`),
    KEY `idx_community_period` (`community_id`, `billing_period`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='账单主表';

CREATE TABLE `bl_payment` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `payment_no` VARCHAR(32) NOT NULL COMMENT '支付单号（幂等键）',
    `total_amount` DECIMAL(12,2) NOT NULL COMMENT '支付总金额',
    `pay_method` VARCHAR(20) NOT NULL DEFAULT 'MOCK' COMMENT '支付方式（WECHAT-微信 ALIPAY-支付宝 MOCK-模拟）',
    `status` VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT '支付状态（PENDING-待支付 SUCCESS-成功 FAILED-失败 CLOSED-已关闭）',
    `owner_id` BIGINT NOT NULL COMMENT '业主ID',
    `owner_name` VARCHAR(64) DEFAULT NULL COMMENT '业主姓名（冗余）',
    `paid_time` DATETIME DEFAULT NULL COMMENT '支付成功时间',
    `expire_time` DATETIME NOT NULL COMMENT '支付过期时间',
    `del_flag` TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记（0-正常 1-删除）',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '创建人',
    `update_by` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '更新人',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_payment_no` (`payment_no`),
    KEY `idx_owner_id` (`owner_id`),
    KEY `idx_status` (`status`),
    KEY `idx_expire_time` (`expire_time`),
    KEY `idx_status_expire` (`status`, `expire_time`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='支付记录表';

CREATE TABLE `bl_payment_bill` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `payment_id` BIGINT NOT NULL COMMENT '支付ID',
    `bill_id` BIGINT NOT NULL COMMENT '账单ID',
    `pay_amount` DECIMAL(12,2) NOT NULL COMMENT '本笔账单支付金额',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`id`),
    KEY `idx_payment_id` (`payment_id`),
    KEY `idx_bill_id` (`bill_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='支付账单关联表';

CREATE TABLE `bl_reduce_record` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `bill_id` BIGINT NOT NULL COMMENT '账单ID',
    `bill_no` VARCHAR(20) DEFAULT NULL COMMENT '账单编号（冗余）',
    `reduce_amount` DECIMAL(12,2) NOT NULL COMMENT '减免金额',
    `reason` VARCHAR(512) NOT NULL COMMENT '减免原因',
    `status` VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT '状态（PENDING-待审批 APPROVED-已审批 REJECTED-已驳回 REVOKED-已撤销）',
    `applicant_id` BIGINT NOT NULL COMMENT '申请人ID',
    `applicant_name` VARCHAR(64) DEFAULT NULL COMMENT '申请人姓名（冗余）',
    `approver_id` BIGINT DEFAULT NULL COMMENT '审批人ID',
    `approver_name` VARCHAR(64) DEFAULT NULL COMMENT '审批人姓名（冗余）',
    `approve_time` DATETIME DEFAULT NULL COMMENT '审批时间',
    `approve_remark` VARCHAR(256) DEFAULT NULL COMMENT '审批备注',
    `del_flag` TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记（0-正常 1-删除）',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '创建人',
    `update_by` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '更新人',
    PRIMARY KEY (`id`),
    KEY `idx_bill_id` (`bill_id`),
    KEY `idx_status` (`status`),
    KEY `idx_applicant_id` (`applicant_id`),
    KEY `idx_approver_id` (`approver_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='减免记录表';

CREATE TABLE `bl_urge_record` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `bill_id` BIGINT NOT NULL COMMENT '账单ID',
    `bill_no` VARCHAR(20) DEFAULT NULL COMMENT '账单编号（冗余）',
    `urge_type` VARCHAR(20) NOT NULL COMMENT '催收方式（MESSAGE-站内消息 SMS-短信 PHONE-电话）',
    `urge_user_id` BIGINT NOT NULL COMMENT '催收人ID',
    `urge_user_name` VARCHAR(64) DEFAULT NULL COMMENT '催收人姓名（冗余）',
    `urge_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '催收时间',
    `feedback` VARCHAR(512) DEFAULT NULL COMMENT '业主反馈',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`id`),
    KEY `idx_bill_id` (`bill_id`),
    KEY `idx_urge_user_id` (`urge_user_id`),
    KEY `idx_urge_time` (`urge_time`),
    KEY `idx_urge_type` (`urge_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='催收记录表';

CREATE TABLE `bl_refund_record` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `bill_id` BIGINT NOT NULL COMMENT '账单ID',
    `bill_no` VARCHAR(20) DEFAULT NULL COMMENT '账单编号（冗余）',
    `refund_amount` DECIMAL(12,2) NOT NULL COMMENT '退款金额（负数表示）',
    `refund_reason` VARCHAR(512) NOT NULL COMMENT '退款原因',
    `operator_id` BIGINT NOT NULL COMMENT '操作人ID',
    `operator_name` VARCHAR(64) DEFAULT NULL COMMENT '操作人姓名（冗余）',
    `refund_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '退款时间',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`id`),
    KEY `idx_bill_id` (`bill_id`),
    KEY `idx_operator_id` (`operator_id`),
    KEY `idx_refund_time` (`refund_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='退款记录表';
